### ISSUE TITLE
Keyfile not being recognoized in default location

### ISSUE THREAD

**Issue by vzeazy** [ilyachch/md_docs-trans-app#14]
Traceback (most recent call last):
  File "app.py", line 18, in <module>
    main()
  File "app.py", line 14, in main
    App().process()
  File "app.py", line 11, in process
    FilesWorker(self.settings.path).process()
  File "/usr/local/lib/python3.5/dist-packages/md_translate/files_worker.py", line 10, in __init__
    self.__validate_folder()
  File "/usr/local/lib/python3.5/dist-packages/md_translate/files_worker.py", line 14, in __validate_folder
    if not os.path.exists(self.__folder_to_process):
  File "/usr/lib/python3.5/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: argument should be string, bytes or integer, not PosixPath

**Comment by ilyachch** [comment]
Hello! I'm very sorry for SO long pause.
If it is still actual for you, I remade project and fixed this problem
