### ISSUE TITLE
A problem with translation into Swedish

### ISSUE THREAD

**Issue by regul1256** [ilyachch/md_docs-trans-app#24]
The prompt displays the following message when processing files from English to Swedish: 
`'charmap' codec can't encode character '\xf6' in position 22: character maps to <undefined>`
There's an encoding problem of words that contain umlaut-letters like ö and other letters that specific to the Swedish alphabet. I've tried it on two different PCs, and the result was the same.

**Comment by ilyachch** [comment]
@regul1256 Hi! I've updated the app, please update and try it again
you can update it with such command:
```
pip install --upgrade md-translate
```
I think it should fail, but an error output should be much richer

please, write here an error output, your OS, python version and full command of launch, e.g:
```
md-translate -s Google -S sv -T ru test.md
```
It will help to localize an error and solve it

also, you can help by providing source text part

**Comment by regul1256** [comment]
@ilyachch Hi, thanks for the response. I've updated the app and did the instructions with the following piece of text: 
**This text is going to be translated into the Swedish language**
Got the same error, and the following log: 
```
Using Russia server backend.
[11:45:02] Processing: sweden-1.md
[11:45:02] Got 1 lines to process 
[11:45:03] Processed 1 lines
[11:45:03] 'charmap' codec can't encode character '\xf6' in position 22: character maps to <undefined>
Traceback (most recent call last):

  File "c:\users\dzhigzhitzhapov\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\Users\dzhigzhitzhapov\AppD...
           │         └ <code object <module> at 0x000001E96CEB5710, file "C:\Users\dzhigzhitzhapov\AppData\Local\Programs\Python\Python38\Scripts\md...
           └ <function _run_code at 0x000001E96CCE8C10>

  File "c:\users\dzhigzhitzhapov\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\Users\dzhigzhitzhapov\AppD...
         └ <code object <module> at 0x000001E96CEB5710, file "C:\Users\dzhigzhitzhapov\AppData\Local\Programs\Python\Python38\Scripts\md...

  File "C:\Users\dzhigzhitzhapov\AppData\Local\Programs\Python\Python38\Scripts\md-translate.exe\__main__.py", line 7, in <module>
> File "c:\users\dzhigzhitzhapov\appdata\local\programs\python\python38\lib\site-packages\md_translate\app.py", line 22, in run   
    App().process()
    └ <class 'md_translate.app.App'>

  File "c:\users\dzhigzhitzhapov\appdata\local\programs\python\python38\lib\site-packages\md_translate\app.py", line 16, in process
    processing_file.translate()
    │               └ <function FileTranslator.translate at 0x000001E96F7ABCA0>
    └ <md_translate.file_translator.FileTranslator object at 0x000001E96F7FFDF0>

  File "c:\users\dzhigzhitzhapov\appdata\local\programs\python\python38\lib\site-packages\md_translate\file_translator.py", line 39, in translate
    self._write_translated_data_to_file()
    │    └ <function FileTranslator._write_translated_data_to_file at 0x000001E96F7ABB80>
    └ <md_translate.file_translator.FileTranslator object at 0x000001E96F7FFDF0>

  File "c:\users\dzhigzhitzhapov\appdata\local\programs\python\python38\lib\site-packages\md_translate\file_translator.py", line 48, in _write_translated_data_to_file
    self.__translating_file.writelines(self.file_contents_with_translation)
    │                                  │    └ ['This text is going to be translated into the Swedish language. \n', '\n', 'Denna text kommer att översättas till svenska.\n']
    │                                  └ <md_translate.file_translator.FileTranslator object at 0x000001E96F7FFDF0>
    └ <md_translate.file_translator.FileTranslator object at 0x000001E96F7FFDF0>

  File "c:\users\dzhigzhitzhapov\appdata\local\programs\python\python38\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           │      │              │     │    │      └ <EncodingMap object at 0x000001E96C59D450>
           │      │              │     │    └ 'strict'
           │      │              │     └ <encodings.cp1251.IncrementalEncoder object at 0x000001E96F7DCFA0>
           │      │              └ 'Denna text kommer att översättas till svenska.\r\n'
           │      └ <built-in function charmap_encode>
           └ <module 'codecs' from 'c:\\users\\dzhigzhitzhapov\\appdata\\local\\programs\\python\\python38\\lib\\codecs.py'>

UnicodeEncodeError: 'charmap' codec can't encode character '\xf6' in position 22: character maps to <undefined>
```

**Comment by ilyachch** [comment]
Great! Thank you!
Now it's much more informative, I'll look how to solve this issue

**Comment by ilyachch** [comment]
https://habr.com/ru/post/579868/

**Comment by ilyachch** [comment]
please, test version 3. In case of any problems, please, open new issue
