### ISSUE TITLE
There is no such driver by url

### ISSUE THREAD

**Issue by 2n-1** [ilyachch/md_docs-trans-app#40]
Hello I'm getting this error when I try to run the following command
`md-translate test.md -F en -T es -P deepl;`

`
Traceback (most recent call last):
  File "/home/amorelli/.local/bin/md-translate", line 8, in <module>
    sys.exit(main())
  File "/home/amorelli/.local/pipx/venvs/md-translate/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/amorelli/.local/pipx/venvs/md-translate/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/amorelli/.local/pipx/venvs/md-translate/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/amorelli/.local/pipx/venvs/md-translate/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/amorelli/.local/pipx/venvs/md-translate/lib/python3.10/site-packages/md_translate/main.py", line 25, in main
    exit(Application(settings).run())
  File "/home/amorelli/.local/pipx/venvs/md-translate/lib/python3.10/site-packages/md_translate/application.py", line 23, in run
    self.run_single_process()
  File "/home/amorelli/.local/pipx/venvs/md-translate/lib/python3.10/site-packages/md_translate/application.py", line 32, in run_single_process
    self.process_file(file_to_process)
  File "/home/amorelli/.local/pipx/venvs/md-translate/lib/python3.10/site-packages/md_translate/application.py", line 117, in process_file
    with translation_provider as provider:
  File "/home/amorelli/.local/pipx/venvs/md-translate/lib/python3.10/site-packages/md_translate/translators/_selenium_base.py", line 55, in __enter__
    service=ChromeService(ChromeDriverManager().install()), options=options
  File "/home/amorelli/.local/pipx/venvs/md-translate/lib/python3.10/site-packages/webdriver_manager/chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "/home/amorelli/.local/pipx/venvs/md-translate/lib/python3.10/site-packages/webdriver_manager/core/manager.py", line 40, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url(os_type))
  File "/home/amorelli/.local/pipx/venvs/md-translate/lib/python3.10/site-packages/webdriver_manager/core/download_manager.py", line 29, in download_file
    response = self._http_client.get(url)
  File "/home/amorelli/.local/pipx/venvs/md-translate/lib/python3.10/site-packages/webdriver_manager/core/http.py", line 36, in get
    self.validate_response(resp)
  File "/home/amorelli/.local/pipx/venvs/md-translate/lib/python3.10/site-packages/webdriver_manager/core/http.py", line 15, in validate_response
    raise ValueError(f"There is no such driver by url {resp.url}")
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/113.0.5672.126/chromedriver_linux64.zip`

Indeed the URL `https://chromedriver.storage.googleapis.com/113.0.5672.126/chromedriver_linux64.zip` returns 404.

Thanks a lot in advance for your help!

**Comment by ilyachch** [comment]
Please, provide the version you are using and OS.
3.0.3 was broken and yanked from pypi.

Also, try to update app. The actual version is 3.0.4. It was updated to use latest available version of chromedriver.

**Comment by ilyachch** [comment]
As there is no any response, I think, I can close the issue.
