### ISSUE TITLE
Needs chrome?

### ISSUE THREAD

**Issue by willwade** [ilyachch/md_docs-trans-app#41]
```

Users/willwade/.local/bin/md-translate docs-de -F eng -T de -P yandex -O
/bin/sh: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome: No such file or directory
/bin/sh: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome: No such file or directory
/bin/sh: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome: No such file or directory
/bin/sh: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome: No such file or directory
/bin/sh: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome: No such file or directory
Traceback (most recent call last):
  File "/Users/willwade/.local/bin/md-translate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/willwade/.local/pipx/venvs/md-translate/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/willwade/.local/pipx/venvs/md-translate/lib/python3.11/site-packages/click/core.py", line 1078, in main


```

etc

I think it just needs to be in the readme you need chrome installed..

**Comment by ilyachch** [comment]
Thank you for your response. You are absolutely right. I've made update to doc.
