### ISSUE TITLE
NotImplementedError: BaseBlock

### ISSUE THREAD

**Issue by jyunhongsu** [ilyachch/md_docs-trans-app#57]
# Contexts

- Edition: Windows 11 Enterprise
- Version: 22H2
- OS build: 22621.2428
- Experience: Windows Feature Experience Pack 1000.22674.1000.0
- Shell: PowerShell

# Error

```bash
DevTools listening on ws://{host:port}/devtools/browser/025bb793-27d8-4d95-b429-cf2522701c83
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "{USER}\.local\bin\md-translate.exe\__main__.py", line 7, in <module>
  File "{USER}\.local\pipx\venvs\md-translate\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{USER}\.local\pipx\venvs\md-translate\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "{USER}\.local\pipx\venvs\md-translate\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{USER}\.local\pipx\venvs\md-translate\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{USER}\.local\pipx\venvs\md-translate\Lib\site-packages\md_translate\main.py", line 25, in main
    exit(Application(settings).run())
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{USER}\.local\pipx\venvs\md-translate\Lib\site-packages\md_translate\application.py", line 23, in run
    self.run_single_process()
  File "{USER}\.local\pipx\venvs\md-translate\Lib\site-packages\md_translate\application.py", line 32, in run_single_process
    self.process_file(file_to_process)
  File "{USER}\.local\pipx\venvs\md-translate\Lib\site-packages\md_translate\application.py", line 124, in process_file
    document.write()
  File "{USER}\.local\pipx\venvs\md-translate\Lib\site-packages\md_translate\document\document.py", line 46, in write
    file_to_write.write_text('\n'.join([self._TRANSLATED_MARK, self.render_translated()]))
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "{USER}\.local\pipx\venvs\md-translate\Lib\site-packages\md_translate\document\document.py", line 59, in render_translated
    rendered_blocks.append(str(block))
                           ^^^^^^^^^^
  File "{USER}\.local\pipx\venvs\md-translate\Lib\site-packages\md_translate\document\blocks.py", line 205, in __str__
    rendered_children.append(f'{mark} {child}')
                             ^^^^^^^^^^^^^^^^^
  File "{USER}\.local\pipx\venvs\md-translate\Lib\site-packages\md_translate\document\blocks.py", line 182, in __str__
    nested_lines = ''.join(map(str, self.nested_children)).splitlines()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{USER}\.local\pipx\venvs\md-translate\Lib\site-packages\md_translate\document\blocks.py", line 16, in __str__
    raise NotImplementedError(self.__class__.__name__)
NotImplementedError: BaseBlock
```

**Comment by ilyachch** [comment]
@jyunhongsu Hello and thank you for issue submission. Could you provide also the text block, there this error happened?
